#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=2GB
#SBATCH --job-name=TwitterDataDump
#SBATCH --mail-type=END
#SBATCH --mail-user=xialiang.liu@nyu.edu
#SBATCH --output=/scratch/xl2053/tweets/logs/batch-%j.log

module load libxslt/intel/1.1.29

RUNDIR=$HOME/GetOldTweets-python
cd $RUNDIR

OUTPUT_PATH=/scratch/xl2053/tweets
NOW=$(date +"%Y-%m-%d-%H:%M:%S")
LOGFILE=$OUTPUT_PATH/logs/batch-$NOW.log

while read USER; do
	python Exporter.py --username "$USER" --since 2010-01-01 --until 2018-04-01 > $OUTPUT_PATH/logs/$USER.log
done <$1

